apiVersion: v1
kind: Service
metadata:
  name: worker-svc
  namespace: ticketing
spec:
  selector:
    app: worker-svc
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
