region: ap-northeast-2

metrics:
  # RDS Aurora
  - aws_namespace: AWS/RDS
    aws_metric_name: CPUUtilization
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average]
    period_seconds: 60

  - aws_namespace: AWS/RDS
    aws_metric_name: DatabaseConnections
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average]
    period_seconds: 60

  - aws_namespace: AWS/RDS
    aws_metric_name: ReplicaLag
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average]
    period_seconds: 30

  - aws_namespace: AWS/RDS
    aws_metric_name: ReadLatency
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average]
    period_seconds: 60

  - aws_namespace: AWS/RDS
    aws_metric_name: WriteLatency
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average]
    period_seconds: 60

  # SQS
  - aws_namespace: AWS/SQS
    aws_metric_name: ApproximateNumberOfMessagesVisible
    aws_dimensions: [QueueName]
    aws_statistics: [Maximum]
    period_seconds: 30

  - aws_namespace: AWS/SQS
    aws_metric_name: ApproximateAgeOfOldestMessage
    aws_dimensions: [QueueName]
    aws_statistics: [Maximum]
    period_seconds: 30

  - aws_namespace: AWS/SQS
    aws_metric_name: NumberOfMessagesSent
    aws_dimensions: [QueueName]
    aws_statistics: [Sum]
    period_seconds: 60

  # ElastiCache Redis
  - aws_namespace: AWS/ElastiCache
    aws_metric_name: CurrConnections
    aws_dimensions: [CacheClusterId]
    aws_statistics: [Average]
    period_seconds: 60

  - aws_namespace: AWS/ElastiCache
    aws_metric_name: DatabaseMemoryUsagePercentage
    aws_dimensions: [CacheClusterId]
    aws_statistics: [Average]
    period_seconds: 60

  - aws_namespace: AWS/ElastiCache
    aws_metric_name: CacheHits
    aws_dimensions: [CacheClusterId]
    aws_statistics: [Sum]
    period_seconds: 60

  - aws_namespace: AWS/ElastiCache
    aws_metric_name: CacheMisses
    aws_dimensions: [CacheClusterId]
    aws_statistics: [Sum]
    period_seconds: 60
